package SintefMaster;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SintefMaster.proto

public final class SintefMaster {
  private SintefMaster() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LatLngOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double Latitude = 1;
    /**
     * <code>required double Latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double Latitude = 1;</code>
     */
    double getLatitude();

    // required double Longitude = 2;
    /**
     * <code>required double Longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double Longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code LatLng}
   *
   * <pre>
   * WGS 84
   * </pre>
   */
  public static final class LatLng extends
      com.google.protobuf.GeneratedMessage
      implements LatLngOrBuilder {
    // Use LatLng.newBuilder() to construct.
    private LatLng(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LatLng(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LatLng defaultInstance;
    public static LatLng getDefaultInstance() {
      return defaultInstance;
    }

    public LatLng getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LatLng(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SintefMaster.internal_static_LatLng_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SintefMaster.internal_static_LatLng_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SintefMaster.LatLng.class, SintefMaster.LatLng.Builder.class);
    }

    public static com.google.protobuf.Parser<LatLng> PARSER =
        new com.google.protobuf.AbstractParser<LatLng>() {
      public LatLng parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LatLng(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LatLng> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double Latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double Latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double Latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // required double Longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double Longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double Longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private void initFields() {
      latitude_ = 0D;
      longitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SintefMaster.LatLng parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.LatLng parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.LatLng parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.LatLng parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.LatLng parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.LatLng parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SintefMaster.LatLng parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SintefMaster.LatLng parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SintefMaster.LatLng parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.LatLng parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SintefMaster.LatLng prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LatLng}
     *
     * <pre>
     * WGS 84
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SintefMaster.LatLngOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SintefMaster.internal_static_LatLng_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SintefMaster.internal_static_LatLng_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SintefMaster.LatLng.class, SintefMaster.LatLng.Builder.class);
      }

      // Construct using SintefMaster.LatLng.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SintefMaster.internal_static_LatLng_descriptor;
      }

      public SintefMaster.LatLng getDefaultInstanceForType() {
        return SintefMaster.LatLng.getDefaultInstance();
      }

      public SintefMaster.LatLng build() {
        SintefMaster.LatLng result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SintefMaster.LatLng buildPartial() {
        SintefMaster.LatLng result = new SintefMaster.LatLng(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SintefMaster.LatLng) {
          return mergeFrom((SintefMaster.LatLng)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SintefMaster.LatLng other) {
        if (other == SintefMaster.LatLng.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SintefMaster.LatLng parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SintefMaster.LatLng) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double Latitude = 1;
      private double latitude_ ;
      /**
       * <code>required double Latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double Latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double Latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double Latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // required double Longitude = 2;
      private double longitude_ ;
      /**
       * <code>required double Longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double Longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double Longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double Longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LatLng)
    }

    static {
      defaultInstance = new LatLng(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LatLng)
  }

  public interface ObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ID = 1;
    /**
     * <code>required string ID = 1;</code>
     */
    boolean hasID();
    /**
     * <code>required string ID = 1;</code>
     */
    java.lang.String getID();
    /**
     * <code>required string ID = 1;</code>
     */
    com.google.protobuf.ByteString
        getIDBytes();

    // required .LatLng Position = 2;
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    boolean hasPosition();
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    SintefMaster.LatLng getPosition();
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    SintefMaster.LatLngOrBuilder getPositionOrBuilder();

    // optional double Heading = 3;
    /**
     * <code>optional double Heading = 3;</code>
     */
    boolean hasHeading();
    /**
     * <code>optional double Heading = 3;</code>
     */
    double getHeading();

    // optional uint64 Timestamp = 4;
    /**
     * <code>optional uint64 Timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 Timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Object}
   */
  public static final class Object extends
      com.google.protobuf.GeneratedMessage
      implements ObjectOrBuilder {
    // Use Object.newBuilder() to construct.
    private Object(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Object(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Object defaultInstance;
    public static Object getDefaultInstance() {
      return defaultInstance;
    }

    public Object getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Object(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iD_ = input.readBytes();
              break;
            }
            case 18: {
              SintefMaster.LatLng.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(SintefMaster.LatLng.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              heading_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SintefMaster.internal_static_Object_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SintefMaster.internal_static_Object_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SintefMaster.Object.class, SintefMaster.Object.Builder.class);
    }

    public static com.google.protobuf.Parser<Object> PARSER =
        new com.google.protobuf.AbstractParser<Object>() {
      public Object parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Object(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Object> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string ID = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object iD_;
    /**
     * <code>required string ID = 1;</code>
     */
    public boolean hasID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ID = 1;</code>
     */
    public java.lang.String getID() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          iD_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .LatLng Position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private SintefMaster.LatLng position_;
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    public SintefMaster.LatLng getPosition() {
      return position_;
    }
    /**
     * <code>required .LatLng Position = 2;</code>
     */
    public SintefMaster.LatLngOrBuilder getPositionOrBuilder() {
      return position_;
    }

    // optional double Heading = 3;
    public static final int HEADING_FIELD_NUMBER = 3;
    private double heading_;
    /**
     * <code>optional double Heading = 3;</code>
     */
    public boolean hasHeading() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double Heading = 3;</code>
     */
    public double getHeading() {
      return heading_;
    }

    // optional uint64 Timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional uint64 Timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 Timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      iD_ = "";
      position_ = SintefMaster.LatLng.getDefaultInstance();
      heading_ = 0D;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, heading_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, heading_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SintefMaster.Object parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.Object parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.Object parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.Object parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.Object parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.Object parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SintefMaster.Object parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SintefMaster.Object parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SintefMaster.Object parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.Object parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SintefMaster.Object prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Object}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SintefMaster.ObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SintefMaster.internal_static_Object_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SintefMaster.internal_static_Object_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SintefMaster.Object.class, SintefMaster.Object.Builder.class);
      }

      // Construct using SintefMaster.Object.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        iD_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (positionBuilder_ == null) {
          position_ = SintefMaster.LatLng.getDefaultInstance();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        heading_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SintefMaster.internal_static_Object_descriptor;
      }

      public SintefMaster.Object getDefaultInstanceForType() {
        return SintefMaster.Object.getDefaultInstance();
      }

      public SintefMaster.Object build() {
        SintefMaster.Object result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SintefMaster.Object buildPartial() {
        SintefMaster.Object result = new SintefMaster.Object(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.heading_ = heading_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SintefMaster.Object) {
          return mergeFrom((SintefMaster.Object)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SintefMaster.Object other) {
        if (other == SintefMaster.Object.getDefaultInstance()) return this;
        if (other.hasID()) {
          bitField0_ |= 0x00000001;
          iD_ = other.iD_;
          onChanged();
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasHeading()) {
          setHeading(other.getHeading());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasID()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        if (!getPosition().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SintefMaster.Object parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SintefMaster.Object) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ID = 1;
      private java.lang.Object iD_ = "";
      /**
       * <code>required string ID = 1;</code>
       */
      public boolean hasID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ID = 1;</code>
       */
      public java.lang.String getID() {
        java.lang.Object ref = iD_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          iD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIDBytes() {
        java.lang.Object ref = iD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ID = 1;</code>
       */
      public Builder setID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ID = 1;</code>
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = getDefaultInstance().getID();
        onChanged();
        return this;
      }
      /**
       * <code>required string ID = 1;</code>
       */
      public Builder setIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }

      // required .LatLng Position = 2;
      private SintefMaster.LatLng position_ = SintefMaster.LatLng.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder> positionBuilder_;
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public SintefMaster.LatLng getPosition() {
        if (positionBuilder_ == null) {
          return position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public Builder setPosition(SintefMaster.LatLng value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public Builder setPosition(
          SintefMaster.LatLng.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public Builder mergePosition(SintefMaster.LatLng value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              position_ != SintefMaster.LatLng.getDefaultInstance()) {
            position_ =
              SintefMaster.LatLng.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = SintefMaster.LatLng.getDefaultInstance();
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public SintefMaster.LatLng.Builder getPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      public SintefMaster.LatLngOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_;
        }
      }
      /**
       * <code>required .LatLng Position = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder>(
                  position_,
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      // optional double Heading = 3;
      private double heading_ ;
      /**
       * <code>optional double Heading = 3;</code>
       */
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double Heading = 3;</code>
       */
      public double getHeading() {
        return heading_;
      }
      /**
       * <code>optional double Heading = 3;</code>
       */
      public Builder setHeading(double value) {
        bitField0_ |= 0x00000004;
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double Heading = 3;</code>
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heading_ = 0D;
        onChanged();
        return this;
      }

      // optional uint64 Timestamp = 4;
      private long timestamp_ ;
      /**
       * <code>optional uint64 Timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 Timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 Timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 Timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Object)
    }

    static {
      defaultInstance = new Object(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Object)
  }

  public interface MoveToOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ObjectID = 1;
    /**
     * <code>required string ObjectID = 1;</code>
     */
    boolean hasObjectID();
    /**
     * <code>required string ObjectID = 1;</code>
     */
    java.lang.String getObjectID();
    /**
     * <code>required string ObjectID = 1;</code>
     */
    com.google.protobuf.ByteString
        getObjectIDBytes();

    // required .LatLng NewPosition = 2;
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    boolean hasNewPosition();
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    SintefMaster.LatLng getNewPosition();
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    SintefMaster.LatLngOrBuilder getNewPositionOrBuilder();
  }
  /**
   * Protobuf type {@code MoveTo}
   */
  public static final class MoveTo extends
      com.google.protobuf.GeneratedMessage
      implements MoveToOrBuilder {
    // Use MoveTo.newBuilder() to construct.
    private MoveTo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MoveTo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MoveTo defaultInstance;
    public static MoveTo getDefaultInstance() {
      return defaultInstance;
    }

    public MoveTo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MoveTo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              objectID_ = input.readBytes();
              break;
            }
            case 18: {
              SintefMaster.LatLng.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = newPosition_.toBuilder();
              }
              newPosition_ = input.readMessage(SintefMaster.LatLng.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(newPosition_);
                newPosition_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SintefMaster.internal_static_MoveTo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SintefMaster.internal_static_MoveTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SintefMaster.MoveTo.class, SintefMaster.MoveTo.Builder.class);
    }

    public static com.google.protobuf.Parser<MoveTo> PARSER =
        new com.google.protobuf.AbstractParser<MoveTo>() {
      public MoveTo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoveTo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MoveTo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string ObjectID = 1;
    public static final int OBJECTID_FIELD_NUMBER = 1;
    private java.lang.Object objectID_;
    /**
     * <code>required string ObjectID = 1;</code>
     */
    public boolean hasObjectID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ObjectID = 1;</code>
     */
    public java.lang.String getObjectID() {
      java.lang.Object ref = objectID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objectID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ObjectID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getObjectIDBytes() {
      java.lang.Object ref = objectID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .LatLng NewPosition = 2;
    public static final int NEWPOSITION_FIELD_NUMBER = 2;
    private SintefMaster.LatLng newPosition_;
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    public boolean hasNewPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    public SintefMaster.LatLng getNewPosition() {
      return newPosition_;
    }
    /**
     * <code>required .LatLng NewPosition = 2;</code>
     */
    public SintefMaster.LatLngOrBuilder getNewPositionOrBuilder() {
      return newPosition_;
    }

    private void initFields() {
      objectID_ = "";
      newPosition_ = SintefMaster.LatLng.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasObjectID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getNewPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getObjectIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, newPosition_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getObjectIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, newPosition_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SintefMaster.MoveTo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.MoveTo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.MoveTo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SintefMaster.MoveTo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SintefMaster.MoveTo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.MoveTo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SintefMaster.MoveTo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SintefMaster.MoveTo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SintefMaster.MoveTo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SintefMaster.MoveTo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SintefMaster.MoveTo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MoveTo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SintefMaster.MoveToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SintefMaster.internal_static_MoveTo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SintefMaster.internal_static_MoveTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SintefMaster.MoveTo.class, SintefMaster.MoveTo.Builder.class);
      }

      // Construct using SintefMaster.MoveTo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objectID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (newPositionBuilder_ == null) {
          newPosition_ = SintefMaster.LatLng.getDefaultInstance();
        } else {
          newPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SintefMaster.internal_static_MoveTo_descriptor;
      }

      public SintefMaster.MoveTo getDefaultInstanceForType() {
        return SintefMaster.MoveTo.getDefaultInstance();
      }

      public SintefMaster.MoveTo build() {
        SintefMaster.MoveTo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SintefMaster.MoveTo buildPartial() {
        SintefMaster.MoveTo result = new SintefMaster.MoveTo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objectID_ = objectID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (newPositionBuilder_ == null) {
          result.newPosition_ = newPosition_;
        } else {
          result.newPosition_ = newPositionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SintefMaster.MoveTo) {
          return mergeFrom((SintefMaster.MoveTo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SintefMaster.MoveTo other) {
        if (other == SintefMaster.MoveTo.getDefaultInstance()) return this;
        if (other.hasObjectID()) {
          bitField0_ |= 0x00000001;
          objectID_ = other.objectID_;
          onChanged();
        }
        if (other.hasNewPosition()) {
          mergeNewPosition(other.getNewPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasObjectID()) {
          
          return false;
        }
        if (!hasNewPosition()) {
          
          return false;
        }
        if (!getNewPosition().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SintefMaster.MoveTo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SintefMaster.MoveTo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ObjectID = 1;
      private java.lang.Object objectID_ = "";
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public boolean hasObjectID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public java.lang.String getObjectID() {
        java.lang.Object ref = objectID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          objectID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getObjectIDBytes() {
        java.lang.Object ref = objectID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public Builder setObjectID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        objectID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public Builder clearObjectID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objectID_ = getDefaultInstance().getObjectID();
        onChanged();
        return this;
      }
      /**
       * <code>required string ObjectID = 1;</code>
       */
      public Builder setObjectIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        objectID_ = value;
        onChanged();
        return this;
      }

      // required .LatLng NewPosition = 2;
      private SintefMaster.LatLng newPosition_ = SintefMaster.LatLng.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder> newPositionBuilder_;
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public boolean hasNewPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public SintefMaster.LatLng getNewPosition() {
        if (newPositionBuilder_ == null) {
          return newPosition_;
        } else {
          return newPositionBuilder_.getMessage();
        }
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public Builder setNewPosition(SintefMaster.LatLng value) {
        if (newPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newPosition_ = value;
          onChanged();
        } else {
          newPositionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public Builder setNewPosition(
          SintefMaster.LatLng.Builder builderForValue) {
        if (newPositionBuilder_ == null) {
          newPosition_ = builderForValue.build();
          onChanged();
        } else {
          newPositionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public Builder mergeNewPosition(SintefMaster.LatLng value) {
        if (newPositionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              newPosition_ != SintefMaster.LatLng.getDefaultInstance()) {
            newPosition_ =
              SintefMaster.LatLng.newBuilder(newPosition_).mergeFrom(value).buildPartial();
          } else {
            newPosition_ = value;
          }
          onChanged();
        } else {
          newPositionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public Builder clearNewPosition() {
        if (newPositionBuilder_ == null) {
          newPosition_ = SintefMaster.LatLng.getDefaultInstance();
          onChanged();
        } else {
          newPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public SintefMaster.LatLng.Builder getNewPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNewPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      public SintefMaster.LatLngOrBuilder getNewPositionOrBuilder() {
        if (newPositionBuilder_ != null) {
          return newPositionBuilder_.getMessageOrBuilder();
        } else {
          return newPosition_;
        }
      }
      /**
       * <code>required .LatLng NewPosition = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder> 
          getNewPositionFieldBuilder() {
        if (newPositionBuilder_ == null) {
          newPositionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SintefMaster.LatLng, SintefMaster.LatLng.Builder, SintefMaster.LatLngOrBuilder>(
                  newPosition_,
                  getParentForChildren(),
                  isClean());
          newPosition_ = null;
        }
        return newPositionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MoveTo)
    }

    static {
      defaultInstance = new MoveTo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MoveTo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LatLng_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LatLng_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Object_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Object_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MoveTo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MoveTo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SintefMaster.proto\"-\n\006LatLng\022\020\n\010Latitu" +
      "de\030\001 \002(\001\022\021\n\tLongitude\030\002 \002(\001\"S\n\006Object\022\n\n" +
      "\002ID\030\001 \002(\t\022\031\n\010Position\030\002 \002(\0132\007.LatLng\022\017\n\007" +
      "Heading\030\003 \001(\001\022\021\n\tTimestamp\030\004 \001(\004\"8\n\006Move" +
      "To\022\020\n\010ObjectID\030\001 \002(\t\022\034\n\013NewPosition\030\002 \002(" +
      "\0132\007.LatLng"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LatLng_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LatLng_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LatLng_descriptor,
              new java.lang.String[] { "Latitude", "Longitude", });
          internal_static_Object_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Object_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Object_descriptor,
              new java.lang.String[] { "ID", "Position", "Heading", "Timestamp", });
          internal_static_MoveTo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MoveTo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MoveTo_descriptor,
              new java.lang.String[] { "ObjectID", "NewPosition", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
